// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivateCurrentOrderStepController from "./activate_current_order_step_controller.js"
application.register("activate-current-order-step", ActivateCurrentOrderStepController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import HomeInfosAppearController from "./home_infos_appear_controller.js"
application.register("home-infos-appear", HomeInfosAppearController)

import NavbarDropdownController from "./navbar_dropdown_controller.js"
application.register("navbar-dropdown", NavbarDropdownController)

import OtherAccountController from "./other_account_controller.js"
application.register("other-account", OtherAccountController)
