// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountSearchAutocompleteController from "./account_search_autocomplete_controller"
application.register("account-search-autocomplete", AccountSearchAutocompleteController)

import AddFileController from "./add_file_controller"
application.register("add-file", AddFileController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CheckDocumentController from "./check_document_controller"
application.register("check-document", CheckDocumentController)

import CheckForAddedContractsController from "./check_for_added_contracts_controller"
application.register("check-for-added-contracts", CheckForAddedContractsController)

import CloseFlashController from "./close_flash_controller"
application.register("close-flash", CloseFlashController)

import HomeFunctionController from "./home_function_controller"
application.register("home-function", HomeFunctionController)

import LoadingSpinnerController from "./loading_spinner_controller"
application.register("loading-spinner", LoadingSpinnerController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarDropdownController from "./navbar_dropdown_controller"
application.register("navbar-dropdown", NavbarDropdownController)

import NavbarResponsivityController from "./navbar_responsivity_controller"
application.register("navbar-responsivity", NavbarResponsivityController)

import OrderAccountCreationController from "./order_account_creation_controller"
application.register("order-account-creation", OrderAccountCreationController)

import ScrollNavbarController from "./scroll_navbar_controller"
application.register("scroll-navbar", ScrollNavbarController)

import ShowPasswordController from "./show_password_controller"
application.register("show-password", ShowPasswordController)

import SubcategoryDropdownController from "./subcategory_dropdown_controller"
application.register("subcategory-dropdown", SubcategoryDropdownController)

import ToggleContractsController from "./toggle_contracts_controller"
application.register("toggle-contracts", ToggleContractsController)

import UpdateChecksController from "./update_checks_controller"
application.register("update-checks", UpdateChecksController)
