// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OrderStepController from "./order_step_controller.js"
application.register("order-step", OrderStepController)

import AddFileController from "./add_file_controller.js"
application.register("add-file", AddFileController)

import CloseFlashController from "./close_flash_controller.js"
application.register("close-flash", CloseFlashController)

import FooterResponsivityController from "./footer_responsivity_controller.js"
application.register("footer-responsivity", FooterResponsivityController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import HomeInfosAppearController from "./home_infos_appear_controller.js"
application.register("home-infos-appear", HomeInfosAppearController)

import NavbarDropdownController from "./navbar_dropdown_controller.js"
application.register("navbar-dropdown", NavbarDropdownController)

import NavbarResponsivityController from "./navbar_responsivity_controller.js"
application.register("navbar-responsivity", NavbarResponsivityController)

import OtherAccountController from "./other_account_controller.js"
application.register("other-account", OtherAccountController)

import RemoveFooterController from "./remove_footer_controller.js"
application.register("remove-footer", RemoveFooterController)

import TransparentNavbarController from "./transparent_navbar_controller.js"
application.register("transparent-navbar", TransparentNavbarController)
