module ActiveStoragePath
  extend ActiveSupport::Concern

  class_methods do
    def has_one_attached_with(name, path:)
      has_one_attached name

      define_method "#{name}=" do |attachable|
        action = super attachable

        return action unless action.is_a? ActiveStorage::Attached::Changes::CreateOne
        return action unless action.blob.service_name == 'google_dev'

        # This is how it is generated by default
        original_key = action.blob.class.generate_unique_secure_token

        # Generate our own key
        if self.class == OrderDocument
          custom_key = "#{Date.today}_#{self.document.name.gsub(' ', '_')}(#{original_key})"
        elsif self.class == OrderAccount
          custom_key = "#{self.account.name}/#{Date.today}_Résiliation_#{self.account.name.gsub(' ', '_')}(#{original_key})"
        end

        # The key is used for path + filename when used. Append path.
        action.blob.key = File.join(instance_exec(&path), custom_key)

        action
      end
    end
  end
end
